language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script: rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - rustfmt --check src/generate/templates/*.rs
  - cargo test --all

branches:
  only:
  - master
